networks:
  si-stvrtok:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: si_project_2025
      MYSQL_USER: si_project_2025
      MYSQL_PASSWORD: si_project_2025
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - si-stvrtok
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - mysql
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./si_project_2025_be:/var/www/html:ro
      - ./si_project_2025_be/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - si-stvrtok
  backend:
    build:
      context: .
      dockerfile: si_project_2025_be/Dockerfile
    volumes:
      - ./si_project_2025_be:/var/www/html
      - ./si_project_2025_be/storage:/var/www/html/storage
      - ./si_project_2025_be/boostrap/cache:/var/www/html/boostrap/cache
    networks:
      - si-stvrtok
    ports:
      - "9000:9000"
    depends_on:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: si_project_2025_fe/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./si_project_2025_fe:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - si-stvrtok


volumes:
  mysql_data: